"""rate effective_to

Revision ID: 4b429719bb9e
Revises: a44bfd4e57d7
Create Date: 2026-10-08 11:31:25.790286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b429719bb9e'
down_revision: Union[str, Sequence[str], None] = 'a44bfd4e57d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_rates', schema=None) as batch_op:
        batch_op.drop_column('effective_to')

    # ### end Alembic commands ###
